Fix non-working code example in typescript.md
statelyai/xstate pull request #2298
Opened 2021-06-13 15:40 UTC by dmitry-guryev

`createMachine` doesn't support this syntax: <LightContext, LightStateSchema, LightEvent>, but `Machine `supports

2021-06-13 16:03 UTC, davidkpiano requested changes

2021-06-13 16:03 UTC, davidkpiano commented on docs/guides/typescript.md
> +const lightMachine = Machine<LightContext, LightStateSchema, LightEvent>({
```suggestion
const lightMachine = createMachine<LightContext, LightEvent>({
```

We want to use `createMachine` and discourage the use of `StateSchema` for now.

2021-06-13 16:22 UTC, VanTanev commented
This is fixed in #2235 >_>

2021-07-20 22:47 UTC, davidkpiano commented
Addressed in https://github.com/statelyai/xstate/pull/2413

2021-07-20 22:47 UTC, closed without merging