Fix recursive errors when passing dom nodes to initial context
statelyai/xstate pull request #3076
Opened 2022-02-22 08:09 UTC by SimeonC

I found this error when using the code attached below in react. Running the code will hang the browser so a bit hard to setup a reproduction. I had a good debugging session on this and discovered that `__context`, `idMap` and a lot of other values (also nested values) sent through in machine have the DOM node ref referenced which is circular and breaks the serializer. It seems that what happens is that the serializer attempts to serialize my entire React tree as it's referenced on the DOM node.

```tsx
inspect({
  serialize: (key: string, value: unknown) => {
    if (key.match(/Ref$/g)) {
      console.log(`xstate inspector dom node "${key}"`, value);
      return `<<omitted dom node>>`;
    }
    return value;
  }
});
// Component
const baseElementRef = React.useRef<HTMLDivElement>(null);
const history = useHistory();
React.useEffect(() => {
  const actor = interpret(
    idlePrompterMachine.withContext({ baseElementRef })
  );
  actor.start();
  history.listen(() => actor.send({ type: 'Page Change' }));
}, []);
```

2022-02-22 09:21 UTC, Andarist requested changes
Could you add a test case that would fail on the main branch?

We already have a basic one for circular context here:
https://github.com/statelyai/xstate/blob/f72691bbb6b929093e32e0e3a46fee1bbdf7c617/packages/xstate-inspect/test/inspect.test.ts#L5

So I wonder where exactly is the difference between this and your use case.

2022-02-22 09:50 UTC, SimeonC commented
@Andarist Thanks for pointing that out, you're correct it isn't a circular reference issue. I've updated the commit message and changelog to reflect this.

About building a reproduction, this doesn't occur in simple reproductions but only in the full app.

It seems that React adds a reference to the virtual DOM to the DOM Node, the virtual DOM references also have parent references so the serialiser attempts to stringify my entire react app via this reference. I have i18n files and context values with a ton of data in them and when it tries to go serialize that when starting the machine my browser hangs for several minutes.

2022-02-22 09:54 UTC, Andarist commented
Just to understand the issue in full - so it's not about crashing but about freezing the main thread for a very long time?

2022-02-22 10:09 UTC, SimeonC commented
I thought about it again - I realised there is a way we can cause a crash with this and I added a test for it.

In my app I assumed it crashed because everything including dev tools froze up and I couldn't manage to get anything out of it (or maybe I just wasn't patient enough). One time I did manage to get a pause in the sources debugger the current code was a good 200+ calls deep in the `decirc` function of the fast stringify.

2022-02-22 10:18 UTC, SimeonC commented on packages/xstate-inspect/test/inspect.test.ts
> +    for (let i = 0; i < 1_000_000; i += 1) {
The actual depth errors start to occur is somewhere around about 5,275 on my machine. Not sure that that value would stay the same so I picked a really big one.

2022-02-24 08:59 UTC, SimeonC commented
@Andarist I created a reproduction sandbox here https://codesandbox.io/s/wispy-leftpad-72f7j7?file=/src/index.js

The reproduction is a bit different to what I was seeing locally, though it does cause noticable lag on the toggle button it doesn't crash the browser here which indicates that possibly my browser would have recovered if I'd given it enough time.

2022-02-24 09:01 UTC, SimeonC commented on packages/xstate-inspect/test/inspect.test.ts
> +    for (let i = 0; i < 1_000_000; i += 1) {
Did redo this back down to 20,000 so it's a bit faster but still shows an error.

2022-02-24 09:40 UTC, Andarist commented
Thanks, I will get to this next week.

2022-02-24 10:28 UTC, SimeonC commented
Awesome, thanks!

As a side note, I referenced this in one of my commits and got a comment from my co-worker that he doesn't use the devTools due to performance as well. His case is when there is a lot of data in context or a lot of events being fired. (He's been using xstate kinda like you would use redux for context).

2022-04-06 13:08 UTC, Andarist commented on .changeset/shy-chefs-chew.md
> +This serialization was unpreventable and could cause the browser to hang for long periods of time.
```suggestion
author: @SimeonC 
author: @Andarist 

Fixed an issue with "maximum call stack size exceeded" errors being thrown when registering a machine with a very deep object in its context despite using a custom `serializer` capable of replacing it.
```

2022-04-06 13:10 UTC, Andarist commented on packages/xstate-inspect/test/inspect.test.ts
> +  it('should not crash when registering machine with very deep context when serializer manages to replace it', (done) => {
I've analyzed this situation further and it turned out that this wasn't about circular references at all. The only required prerequisite for the crash was a very deep object in context.

2022-04-06 13:11 UTC, Andarist commented on packages/xstate-inspect/src/serialize.ts
> +  return selectivelyStringify(machine.definition, ['context'], replacer);
I basically limit what is being stringified here as this should be everything that has to be potentially replaced. Previously we were passing the whole `machine` and it referenced context in a couple of properties other than `context` (such as `_context`, `config` and maybe something else too)

2022-04-06 13:29 UTC, davidkpiano commented on packages/xstate-inspect/src/serialize.ts
> +): string {
```suggestion
  stateToStringify: AnyState,
  replacer?: Replacer
): string {
  const { machine: _machine, configuration: _configuration, ...state } = stateToStringify;
```

Alternative approach that doesn't destructure in the args (which might not look good for intellisense)

2022-04-06 13:30 UTC, davidkpiano approved these changes
Approved with tiny nit suggestion 👍

2022-04-06 20:46 UTC, merged

2022-04-07 01:44 UTC, SimeonC commented
Awesome, thanks for finishing this up!