Add ability to spawn actor from any logic
statelyai/xstate pull request #4724
Opened 2024-02-04 03:06 UTC by davidkpiano

This PR adds the ability for any actor logic to spawn an actor, which is a core tenet of the actor model.

2024-02-05 11:07 UTC, Andarist commented on packages/core/src/types.ts
> +  spawn: (logic: AnyActorLogic) => AnyActorRef;
```suggestion
  spawnChild: (logic: AnyActorLogic) => AnyActorRef;
```

2024-02-05 11:08 UTC, Andarist commented on packages/core/src/types.ts
> +  spawn: (logic: AnyActorLogic) => AnyActorRef;
This has to become generic so people could actually have some type safety here

2024-02-05 11:11 UTC, Andarist commented on packages/core/src/createActor.ts
> +        return actor;
when it is meant to be started?

2024-02-05 15:02 UTC, davidkpiano commented on packages/core/src/createActor.ts
> +        return actor;
I knew I was forgetting something!

2024-02-09 20:05 UTC, Andarist commented on packages/core/src/createActor.ts
> +        }
what about the actors spawned when `this._processingStatus === ProcessingStatus.NotStarted`?

2024-02-09 20:07 UTC, Andarist commented on packages/core/src/createActor.ts
> +        actorOptions?: ActorOptions<T>
this should reuse the type tricks from here: https://github.com/statelyai/xstate/blob/8a7ea9eb5faca407890cfa597eca2915660ab6bd/packages/core/src/createActor.ts#L763-L770

2024-02-09 20:09 UTC, Andarist commented on packages/core/src/actors/callback.ts
> +  spawn: ActorScope<any, any>['spawnChild'];
shouldn't all of those actor logics receive `stopChild` as well?

2024-02-09 20:12 UTC, Andarist requested changes
There is a substantial problem with this PR that is somewhat mentioned in this comment here:
https://github.com/statelyai/xstate/blob/91549ce8a6a5105b3d354ca442ea5c058e58e206/packages/core/src/createActor.ts#L588-L592

When the parent actor gets stopped its children should get stopped too. There is no mechanism implemented here that would achieve this for this new functionality.

2024-07-21 21:05 UTC, davidkpiano commented
> 831aeec

[831aeec](https://github.com/statelyai/xstate/pull/4724/commits/831aeecc9a0a17f297dccfac4c2099be4d328d07)

2024-07-21 21:06 UTC, davidkpiano commented
> There is a substantial problem with this PR that is somewhat mentioned in this comment here:
> 
> https://github.com/statelyai/xstate/blob/91549ce8a6a5105b3d354ca442ea5c058e58e206/packages/core/src/createActor.ts#L588-L592
> 
> When the parent actor gets stopped its children should get stopped too. There is no mechanism implemented here that would achieve this for this new functionality.

[831aeec](https://github.com/statelyai/xstate/pull/4724/commits/831aeecc9a0a17f297dccfac4c2099be4d328d07)

2026-05-24 10:56 UTC, davidkpiano commented
Bringing this to v6.

2026-05-24 10:56 UTC, closed without merging